Add files via upload
degtevkonstantin/module pull request #16
Opened 2023-01-31 11:50 UTC by degtevkonstantin

2023-02-03 10:58 UTC, baklanovairina requested changes

2023-02-03 10:58 UTC, baklanovairina commented on script_15.js
> +const filtMultiplicationBy2 =  (array) => {
filtMultiplicationBy2 - некорректное название 
и по моему есть лишний пробел в строке

2023-02-03 10:58 UTC, baklanovairina commented on script_15.js
> +let arr = [1, 2, 3, 4];
const

2023-02-03 10:58 UTC, baklanovairina commented on script_15.js
> +  newArr = array.filter((x) => x % 2 == 0);
что такое x??

2023-02-03 10:58 UTC, baklanovairina commented on script_15.js
> +const filtMultiplicationBy2 =  (array) => {
у функции 3 параметра, а не один

2023-02-03 10:58 UTC, baklanovairina commented on script_15.js
> +  array = newArr.map((x) => x*2);
и здесь что такое x?

2023-02-08 11:00 UTC, baklanovairina requested changes

2023-02-08 11:00 UTC, baklanovairina commented on script_15.js
> +  array = newArr.map(transformation);
нет идентификатора и почему исходный массив мутирует?

2023-02-13 12:19 UTC, baklanovairina approved these changes

2023-02-16 13:33 UTC, degtevkonstantin commented
[](url)

2023-02-16 13:33 UTC, closed without merging